import {RoverBody} from '../../embodiment/rover/body.mjs';
const DIRS=[[1,0],[0,1],[-1,0],[0,-1]];
export class BrokenWorld {
 constructor({clock=()=>Date.now(),externalMutationAt=3}={}){this.clock=clock;this.externalMutationAt=externalMutationAt;this.body=new RoverBody({x:1,y:2,energy:20});this.energy=20;this.hazard={cells:[{x:6,y:2}],cost:2};this.arena={width:10,height:5,corridors:['west_corridor','east_corridor'],obstacles:[{x:3,y:1},{x:7,y:3}],goalRegion:{xMin:8,xMax:9,yMin:1,yMax:3},door:{x:5,y:2,closed:true,passage:'central'},barriers:[{x:5,yMin:0,yMax:4,controlledBy:'central_door'}]};this.events=[];this.stepCount=0;this.mutationApplied=false;}
 currentState(){return {body:this.body.snapshot(),energy:this.energy,hazard:{...this.hazard},door:{...this.arena.door},step:this.stepCount};}
 log(type,detail={}){const e={id:this.events.length+1,timestamp:this.clock(),type,state:this.currentState(),detail};this.events.push(e);return e;}
 start(){return this.log('EXPECTED',{fact:'door_state',value:'closed',basis:'initial_logged_state'});}
 observe(){const cs=this.arena.obstacles.concat([{x:5,y:2}]);const n=Math.min(...cs.map(c=>Math.abs(c.x-this.body.x)+Math.abs(c.y-this.body.y)));return {visual_field:{corridor:this.body.x<5?'west_corridor':'east_corridor',nearest_obstacle_distance:n},proximity:{nearest_distance:n},collision:{blocked:false},gradients:{energy:this.energy,hazard:this.hazard.cells.some(c=>c.x===this.body.x&&c.y===this.body.y)},energy:{remaining:this.energy},event:{last:this.events.at(-1)?.type??null}};}
 canEnter(t,{doorClosed=this.arena.door.closed}={}){if(t.x<0||t.x>=this.arena.width||t.y<0||t.y>=this.arena.height)return false;if(this.arena.obstacles.some(c=>c.x===t.x&&c.y===t.y))return false;if(doorClosed&&t.x===5)return false;return true;}
 isGoal(s=this.body){const g=this.arena.goalRegion;return s.x>=g.xMin&&s.x<=g.xMax&&s.y>=g.yMin&&s.y<=g.yMax;}
 reachableWithoutDoor(){const q=[{x:1,y:2}],seen=new Set(['1,2']);while(q.length){const h=q.shift();if(this.isGoal(h))return true;for(const [dx,dy] of DIRS){const n={x:h.x+dx,y:h.y+dy},k=`${n.x},${n.y}`;if(!seen.has(k)&&this.canEnter(n,{doorClosed:true})){seen.add(k);q.push(n);}}}return false;}
 mutateExternally({open=true,timestamp=this.clock()}={}){if(this.mutationApplied)return null;this.arena.door.closed=!open;this.mutationApplied=true;const m=this.log('WORLD_MUTATION',{source:'external',timestamp,change:{door_closed:this.arena.door.closed}});const e=this.events.find(x=>x.type==='EXPECTED');this.log('OBSERVED',{sourceEvent:m.id,observation:{door_state:this.arena.door.closed?'closed':'open'}});this.log('CONTRADICTION',{sourceEvents:[e?.id,m.id].filter(Boolean),expected:'closed',observed:this.arena.door.closed?'closed':'open'});this.log('EXECUTIVE RESPONSE',{sourceEvent:m.id,response:'update_policy_pending'});this.log('SUBSTRATE RESPONSE',{sourceEvent:m.id,response:'recurrent_state_update_pending'});this.log('NEW ACTION',{sourceEvent:m.id,action:'forward',basis:'logged-state'});return m;}
 applyAction(action){this.stepCount++;if(this.stepCount===this.externalMutationAt)this.mutateExternally({open:true,timestamp:this.clock()});const p=this.body.proposal(action);const r=this.body.apply(p,{canMove:t=>this.canEnter(t)});if(r.status==='MOVED'&&this.hazard.cells.some(c=>c.x===this.body.x&&c.y===this.body.y))this.energy=Math.max(0,this.energy-this.hazard.cost);this.log('OBSERVED',{action,result:r,senses:this.observe()});this.log('SUBSTRATE RESPONSE',{action,result:r.status,basis:'logged-state'});return r;}
 run(actions=[]){if(!this.events.some(e=>e.type==='EXPECTED'))this.start();for(const a of actions)this.applyAction(a);return {mode:'SUBSTRATE_ONLY',reachedGoal:this.isGoal(),state:this.currentState(),events:this.events};}
}
