import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createNeurocontrol } from '../src/neurocontrol/index.mjs';

const checkpointDir = 'artifacts/checkpoints';
const runtimeState = { membrane: { mean: -62 }, firing: { rate: 3 }, selectedPopulations: { central: 1 }, sensoryInjection: { antenna: 0.2 }, descendingActivity: { command: 0 }, modulation: { gain: 1 }, mode: 'stub' };
let restoreCalls = 0;
const runtime = { ...runtimeState, inspect: () => runtimeState, checkpointState: () => runtimeState, restore: () => { restoreCalls += 1; }, apply: () => { throw new Error('DeltaX actuator must not be called by experimenter perturbations'); } };
const h = createNeurocontrol({ runtime, runId: 'test-run', seeds: { random: 7 }, objective: { target: 'replay' }, environment: { world: 'stub' }, checkpointDir });
const initial = h.inspect();
assert.equal(initial.actor, 'EXPERIMENTER');
assert.equal(initial.authority, 'OBSERVATION_ONLY');
const cp = h.checkpoint({ id: 'neurocontrol-roundtrip' });
assert.ok(fs.existsSync(cp.path));
assert.equal(cp.event_ledger.events.at(-1).type, 'neurocontrol_checkpoint');
h.restore(cp.path);
assert.equal(restoreCalls, 1);
assert.deepEqual(h.seeds, { random: 7 });
const beforePerturb = h.inspect();
h.perturb({ type: 'silence_population', population: 'central' });
const afterPerturb = h.inspect();
assert.deepEqual(afterPerturb.membrane, beforePerturb.membrane);
assert.deepEqual(afterPerturb.firing, beforePerturb.firing);
assert.deepEqual(afterPerturb.selectedPopulations, beforePerturb.selectedPopulations);
assert.equal(afterPerturb.perturbations.silencedPopulations[0], 'central');
assert.throws(() => h.perturb({ actor: 'DeltaX', type: 'silence_population', population: 'unauthorized' }), /experimenter-only/);
const diff = h.compare(cp.path, { interventions: [{ type: 'scale_regional_gain', region: 'central', scale: 2 }] });
assert.equal(diff.schema, 'neurocontrol.compare.v1');
assert.equal(diff.actor, 'EXPERIMENTER');
assert.equal(diff.diverged, true);
assert.ok(diff.divergence.paths.length > 0);
assert.ok(fs.existsSync(diff.path));
const eventTypes = h.ledger.events.map((event) => event.type);
for (const type of ['neurocontrol_checkpoint', 'neurocontrol_restore', 'neurocontrol_perturb', 'neurocontrol_compare']) assert.ok(eventTypes.includes(type));
assert.ok(h.ledger.events.every((event) => event.actor === 'EXPERIMENTER'));
fs.rmSync(cp.path, { force: true });
fs.rmSync(diff.path, { force: true });
console.log('Neurocontrol tests: PASS');
