import { executiveSource, sourceCopy, listValue } from './state.mjs';
const $=id=>document.getElementById(id), state={ledger:null,running:false,elapsed:0,events:[],lesion:null,checkpoint:null};
const put=(id,v)=>$(id).textContent=v==null||v===''?'—':String(v);
const vals=v=>listValue(v).map(x=>typeof x==='object'?(x.name??x.id??JSON.stringify(x)):x);
const list=(id,v,empty)=>{const a=vals(v);$(id).innerHTML=a.length?a.map(x=>`<li>${x}</li>`).join(''):`<li class="muted">${empty}</li>`};
function log(msg){state.events.unshift(msg);$('run-log').innerHTML=state.events.slice(0,5).map(x=>`<li>${x}</li>`).join('')||'<li class="muted">Ready.</li>';}
function source(d){const s=executiveSource(d?.executive_source),b=$('executive-badge');b.textContent='SOURCE: '+s;b.className='badge '+s;$('source-note').textContent=sourceCopy(s);$('authority-tag').textContent=s==='canonical_api'?'CANONICAL AUTHORITY':s==='stub'?'STUB · NOT DELTAX':'NO AUTHORITY';put('goal',d?.goal??d?.current_goal);put('modulation',d?.modulation);put('executive-output',d?.executive_output??d?.output);put('vetoes',d?.vetoes);list('candidates',d?.candidates,'No candidate ledger loaded.');list('contradictions',d?.contradictions,'No contradiction ledger loaded.');list('history',d?.transition_history,'No transitions loaded');}
function telemetry(d){const t=d?.telemetry??d?.substrate??{},r=t.regions??d?.regional_activity??{},a=Object.entries(r);$('activity-bars').innerHTML=a.length?a.slice(0,10).map(([n,v])=>`<div class="activity-bar" style="height:${Math.max(5,Math.min(100,Number(v)||0))}%"><em>${n}</em></div>`).join(''):'<div class="empty-state">Waiting for harness telemetry…</div>';put('spike-total',t.spikes??t.spike_count);put('sensory-value',t.sensory??r.sensory);put('descending-value',t.descending??r.descending);$('intervention-callout').classList.toggle('hidden',!(d?.intervention_active??d?.intervention));}
function world(d){const w=d?.world??{},ev=w.events??d?.world_events??[];put('objective',w.objective??d?.objective??'objective · unavailable');put('world-mode',w.mode??d?.mode??'observe');put('event-count',Array.isArray(ev)?ev.length:'');put('rover-status',w.rover_status??d?.rover_status??'idle');list('world-events',ev,'No mutation events in view.');}
function draw(){const c=$('world-canvas'),x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#07131a';x.fillRect(0,0,w,h);x.strokeStyle='#163541';for(let i=0;i<w;i+=34){x.beginPath();x.moveTo(i,0);x.lineTo(i,h);x.stroke()}x.strokeStyle='#5ee0d1';x.beginPath();x.moveTo(0,h-42);x.lineTo(w,h-42);x.stroke();x.fillStyle='#80a9ff';x.fillRect(116,h-76,70,29);x.fillStyle='#071018';x.fillRect(127,h-69,15,13);x.fillRect(159,h-69,15,13);x.fillStyle='#5ee0d1';x.beginPath();x.arc(128,h-43,10,0,7);x.arc(174,h-43,10,0,7);x.fill();x.fillStyle='#8da1aa';x.font='12px monospace';x.fillText(state.lesion?`lesion: ${state.lesion}`:'rover / simple view',18,24);}
function render(d=state.ledger){source(d||{});$('checkpoint-empty').hidden=Boolean(d);telemetry(d||{});world(d||{});draw();}
function time(s){const m=Math.floor(s/60),q=(s%60).toFixed(1).padStart(4,'0');return `t+${String(m).padStart(2,'0')}:${q}`;}
function running(v){state.running=v;$('run-state').textContent=v?'RUNNING':'PAUSED';$('run-state').classList.toggle('running',v);put('rover-status',v?'active':'idle');}
setInterval(()=>{if(state.running){state.elapsed+=.1;put('sim-time',time(state.elapsed));}},100);
$('start-btn').onclick=()=>{running(true);log('run started (local observatory)');$('control-status').textContent='Local timer running; authoritative state remains the headless harness ledger.'};
$('pause-btn').onclick=()=>{running(false);log('run paused')};
$('reset-btn').onclick=()=>{running(false);state.elapsed=0;state.events=[];state.lesion=null;put('sim-time',time(0));render();log('local view reset')};
$('runtime-mode').onchange=e=>{log('runtime selected: '+e.target.value);$('control-status').textContent=e.target.value+' selected. Badge changes only when that source appears in harness telemetry.'};
$('mutate-btn').onclick=()=>{log('world mutation requested');$('control-status').textContent='Mutation request recorded locally; run the harness to create an authoritative world event.'};
$('checkpoint-btn').onclick=()=>{state.checkpoint=JSON.parse(JSON.stringify({ledger:state.ledger,elapsed:state.elapsed,lesion:state.lesion}));log('checkpoint captured')};
$('restore-btn').onclick=()=>{if(!state.checkpoint)return log('restore skipped: no local checkpoint');state.elapsed=state.checkpoint.elapsed;state.lesion=state.checkpoint.lesion;render();log('checkpoint restored')};
$('lesion-btn').onclick=()=>{state.lesion=$('lesion-target').value;render();log('lesion requested: '+state.lesion);$('control-status').textContent='Experimenter-labeled lesion shown locally; causal result comes from harness artifacts.'};$('clear-lesion-btn').onclick=()=>{state.lesion=null;render();log('lesion cleared')};
$('export-btn').onclick=()=>{const rows=[{type:'observatory_export',exported_at:new Date().toISOString(),executive_source:executiveSource(state.ledger?.executive_source),ledger:state.ledger,local_events:state.events,elapsed:state.elapsed,lesion:state.lesion},{type:'honesty_note',text:'Neural activity is telemetry; stub output is not genuine DeltaX.'}].map(JSON.stringify).join('\n')+'\n';const blob=new Blob([rows],{type:'application/x-ndjson'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='entity-observatory-run.jsonl';a.click();log('JSONL export downloaded')};
async function load(){try{const r=await fetch('./artifacts/checkpoints/causal-intervention-8.json');if(!r.ok)throw Error();state.ledger=await r.json();$('connection-state').textContent='ARTIFACT LOADED';render()}catch{$('connection-state').textContent='NO TELEMETRY';render({})}}
render({});load();
